server:
  port: 9000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.username: myuser
spring.datasource.password: password
spring.datasource.url: jdbc:mysql://localhost:3306/mydatabase?createDatabaseIfNotExist=true
